#!/usr/bin/env python3

# Categories: key -> {en, de}
CATEGORIES = {
    "alcohol": {"en": "Alcohol", "de": "Alkohol"},
    "baby": {"en": "Baby", "de": "Baby"},
    "baking_ingredients": {"en": "Baking Ingredients", "de": "Backzutaten"},
    "bakery": {"en": "Bakery", "de": "Bäckerei"},
    "canned_goods": {"en": "Canned & Jarred Goods", "de": "Dosen und Gläser"},
    "electronics": {"en": "Electronics", "de": "Elektronik"},
    "ready_meals": {"en": "Ready Meals", "de": "Fertiggerichte"},
    "fish": {"en": "Fish & Seafood", "de": "Fisch und Meeresfrüchte"},
    "meat": {"en": "Meat", "de": "Fleisch"},
    "health": {"en": "Health", "de": "Gesundheit"},
    "beverages": {"en": "Beverages", "de": "Getränke"},
    "condiments_spices": {
        "en": "Condiments, Sauces & Oils",
        "de": "Gewürze, Saucen, Öle",
    },
    "home_garden": {"en": "Home & Garden", "de": "Haus und Garten"},
    "pets": {"en": "Pets", "de": "Haustiere"},
    "coffee_tea": {"en": "Coffee & Tea", "de": "Kaffee und Tee"},
    "clothing": {"en": "Clothing", "de": "Kleidung"},
    "cosmetics_hygiene": {"en": "Cosmetics & Hygiene", "de": "Kosmetik und Hygiene"},
    "dairy_eggs": {"en": "Dairy & Eggs", "de": "Milchprodukte und Eier"},
    "fruits_vegetables": {"en": "Fruits & Vegetables", "de": "Obst und Gemüse"},
    "cleaning_laundry": {"en": "Cleaning & Laundry", "de": "Reinigung und Wäsche"},
    "stationery": {"en": "Stationery", "de": "Schreibwaren"},
    "snacks_sweets": {"en": "Snacks & Sweets", "de": "Snacks und Süßigkeiten"},
    "other": {"en": "Other", "de": "Sonstiges"},
    "frozen_foods": {"en": "Frozen Foods", "de": "Tiefkühlkost"},
    "dry_goods": {"en": "Dry Goods", "de": "Trockene Waren"},
}

# Base products: list of (category_key, en_name, de_name)
BASE_PRODUCTS = [
    # Fruits & Vegetables
    ("fruits_vegetables", "Apple", "Apfel"),
    ("fruits_vegetables", "Banana", "Banane"),
    ("fruits_vegetables", "Orange", "Orange"),
    ("fruits_vegetables", "Mango", "Mango"),
    ("fruits_vegetables", "Pineapple", "Ananas"),
    ("fruits_vegetables", "Strawberry", "Erdbeere"),
    ("fruits_vegetables", "Blueberry", "Heidelbeere"),
    ("fruits_vegetables", "Raspberry", "Himbeere"),
    ("fruits_vegetables", "Blackberry", "Brombeere"),
    ("fruits_vegetables", "Grapes", "Weintrauben"),
    ("fruits_vegetables", "Watermelon", "Wassermelone"),
    ("fruits_vegetables", "Cantaloupe", "Cantaloupe-Melone"),
    ("fruits_vegetables", "Peach", "Pfirsich"),
    ("fruits_vegetables", "Pear", "Birne"),
    ("fruits_vegetables", "Plum", "Pflaume"),
    ("fruits_vegetables", "Cherry", "Kirsche"),
    ("fruits_vegetables", "Apricot", "Aprikose"),
    ("fruits_vegetables", "Kiwi", "Kiwi"),
    ("fruits_vegetables", "Papaya", "Papaya"),
    ("fruits_vegetables", "Pomegranate", "Granatapfel"),
    ("fruits_vegetables", "Lemon", "Zitrone"),
    ("fruits_vegetables", "Lime", "Limette"),
    ("fruits_vegetables", "Grapefruit", "Grapefruit"),
    ("fruits_vegetables", "Coconut", "Kokosnuss"),
    ("fruits_vegetables", "Avocado", "Avocado"),
    ("fruits_vegetables", "Tomato", "Tomate"),
    ("fruits_vegetables", "Cherry Tomato", "Cocktailtomate"),
    ("fruits_vegetables", "Cucumber", "Gurke"),
    ("fruits_vegetables", "Bell Pepper", "Paprika"),
    ("fruits_vegetables", "Red Pepper", "Rote Paprika"),
    ("fruits_vegetables", "Green Pepper", "Grüne Paprika"),
    ("fruits_vegetables", "Yellow Pepper", "Gelbe Paprika"),
    ("fruits_vegetables", "Chili Pepper", "Chilischote"),
    ("fruits_vegetables", "Jalapeño", "Jalapeño"),
    ("fruits_vegetables", "Zucchini", "Zucchini"),
    ("fruits_vegetables", "Eggplant", "Aubergine"),
    ("fruits_vegetables", "Broccoli", "Brokkoli"),
    ("fruits_vegetables", "Cauliflower", "Blumenkohl"),
    ("fruits_vegetables", "Cabbage", "Kohl"),
    ("fruits_vegetables", "Red Cabbage", "Rotkohl"),
    ("fruits_vegetables", "Brussels Sprouts", "Rosenkohl"),
    ("fruits_vegetables", "Kale", "Grünkohl"),
    ("fruits_vegetables", "Spinach", "Spinat"),
    ("fruits_vegetables", "Lettuce", "Kopfsalat"),
    ("fruits_vegetables", "Iceberg Lettuce", "Eisbergsalat"),
    ("fruits_vegetables", "Rocket", "Rucola"),
    ("fruits_vegetables", "Chard", "Mangold"),
    ("fruits_vegetables", "Leek", "Lauch"),
    ("fruits_vegetables", "Onion", "Zwiebel"),
    ("fruits_vegetables", "Red Onion", "Rote Zwiebel"),
    ("fruits_vegetables", "Spring Onion", "Frühlingszwiebel"),
    ("fruits_vegetables", "Garlic", "Knoblauch"),
    ("fruits_vegetables", "Shallot", "Schalotte"),
    ("fruits_vegetables", "Carrot", "Karotte"),
    ("fruits_vegetables", "Parsnip", "Pastinake"),
    ("fruits_vegetables", "Turnip", "Rübe"),
    ("fruits_vegetables", "Beetroot", "Rote Bete"),
    ("fruits_vegetables", "Radish", "Radieschen"),
    ("fruits_vegetables", "Sweet Potato", "Süßkartoffel"),
    ("fruits_vegetables", "Potato", "Kartoffel"),
    ("fruits_vegetables", "Butternut Squash", "Butternusskürbis"),
    ("fruits_vegetables", "Pumpkin", "Kürbis"),
    ("fruits_vegetables", "Corn", "Mais"),
    ("fruits_vegetables", "Peas", "Erbsen"),
    ("fruits_vegetables", "Green Beans", "Grüne Bohnen"),
    ("fruits_vegetables", "Asparagus", "Spargel"),
    ("fruits_vegetables", "Artichoke", "Artischocke"),
    ("fruits_vegetables", "Fennel", "Fenchel"),
    ("fruits_vegetables", "Celery", "Sellerie"),
    ("fruits_vegetables", "Celeriac", "Knollensellerie"),
    ("fruits_vegetables", "Mushroom", "Champignon"),
    ("fruits_vegetables", "Shiitake Mushroom", "Shiitake-Pilz"),
    ("fruits_vegetables", "Portobello Mushroom", "Portobello-Pilz"),
    ("fruits_vegetables", "Ginger", "Ingwer"),
    ("fruits_vegetables", "Turmeric", "Kurkuma"),
    ("fruits_vegetables", "Herbs Mix", "Kräutermischung"),
    ("fruits_vegetables", "Basil", "Basilikum"),
    ("fruits_vegetables", "Parsley", "Petersilie"),
    ("fruits_vegetables", "Mint", "Minze"),
    ("fruits_vegetables", "Rosemary", "Rosmarin"),
    ("fruits_vegetables", "Thyme", "Thymian"),
    ("fruits_vegetables", "Chives", "Schnittlauch"),
    ("fruits_vegetables", "Dill", "Dill"),
    ("fruits_vegetables", "Coriander", "Koriander"),
    ("fruits_vegetables", "Lemongrass", "Zitronengras"),
    ("fruits_vegetables", "Fig", "Feige"),
    ("fruits_vegetables", "Date", "Dattel"),
    ("fruits_vegetables", "Passion Fruit", "Maracuja"),
    ("fruits_vegetables", "Dragon Fruit", "Drachenfrucht"),
    ("fruits_vegetables", "Lychee", "Litschi"),
    ("fruits_vegetables", "Guava", "Guave"),
    ("fruits_vegetables", "Starfruit", "Karambole"),
    ("fruits_vegetables", "Persimmon", "Kaki"),
    ("fruits_vegetables", "Quince", "Quitte"),
    ("fruits_vegetables", "Okra", "Okra"),
    ("fruits_vegetables", "Bok Choy", "Pak Choi"),
    ("fruits_vegetables", "Endive", "Endivie"),
    ("fruits_vegetables", "Watercress", "Brunnenkresse"),
    ("fruits_vegetables", "Savoy Cabbage", "Wirsing"),
    ("fruits_vegetables", "Kohlrabi", "Kohlrabi"),
    ("fruits_vegetables", "Plantain", "Kochbanane"),
    # Meat
    ("meat", "Chicken Breast", "Hühnerbrust"),
    ("meat", "Chicken Thigh", "Hähnchenschenkel"),
    ("meat", "Whole Chicken", "Ganzes Hähnchen"),
    ("meat", "Chicken Wings", "Hähnchenflügel"),
    ("meat", "Turkey Breast", "Putenbrust"),
    ("meat", "Ground Turkey", "Hackfleisch vom Truthahn"),
    ("meat", "Duck Breast", "Entenbrust"),
    ("meat", "Beef Steak", "Rindersteak"),
    ("meat", "Ground Beef", "Rinderhackfleisch"),
    ("meat", "Beef Roast", "Rinderbraten"),
    ("meat", "Beef Ribs", "Rinderrippen"),
    ("meat", "Veal", "Kalbfleisch"),
    ("meat", "Pork Chop", "Schweinekotelette"),
    ("meat", "Pork Loin", "Schweinefilet"),
    ("meat", "Ground Pork", "Schweinehackfleisch"),
    ("meat", "Pork Ribs", "Schweinerippchen"),
    ("meat", "Bacon", "Speck"),
    ("meat", "Ham", "Schinken"),
    ("meat", "Salami", "Salami"),
    ("meat", "Sausage", "Wurst"),
    ("meat", "Bratwurst", "Bratwurst"),
    ("meat", "Chorizo", "Chorizo"),
    ("meat", "Prosciutto", "Prosciutto"),
    ("meat", "Pancetta", "Pancetta"),
    ("meat", "Lamb Chop", "Lammkotelett"),
    ("meat", "Lamb Rack", "Lammrücken"),
    ("meat", "Ground Lamb", "Lammhackfleisch"),
    ("meat", "Venison", "Wildfleisch"),
    ("meat", "Rabbit", "Kaninchen"),
    ("meat", "Liver", "Leber"),
    ("meat", "Beef Mince", "Rindermett"),
    ("meat", "Chicken Fillet", "Hähnchenfilet"),
    ("meat", "Turkey Mince", "Putenhackfleisch"),
    ("meat", "Pork Belly", "Schweinebauch"),
    ("meat", "Beef Brisket", "Rinderbrust"),
    ("meat", "Short Ribs", "Short Ribs"),
    ("meat", "Chicken Drumstick", "Hähnchenkeulen"),
    ("meat", "Beef Sirloin", "Roastbeef"),
    ("meat", "Beef Tenderloin", "Rinderfilet"),
    ("meat", "T-Bone Steak", "T-Bone-Steak"),
    # Fish & Seafood
    ("fish", "Salmon Fillet", "Lachsfilet"),
    ("fish", "Whole Salmon", "Ganzer Lachs"),
    ("fish", "Smoked Salmon", "Räucherlachs"),
    ("fish", "Tuna Steak", "Thunfischsteak"),
    ("fish", "Canned Tuna", "Thunfisch aus der Dose"),
    ("fish", "Cod Fillet", "Kabeljaufilet"),
    ("fish", "Haddock", "Schellfisch"),
    ("fish", "Tilapia", "Tilapia"),
    ("fish", "Sea Bass", "Wolfsbarsch"),
    ("fish", "Sea Bream", "Dorade"),
    ("fish", "Trout", "Forelle"),
    ("fish", "Mackerel", "Makrele"),
    ("fish", "Herring", "Hering"),
    ("fish", "Sardines", "Sardinen"),
    ("fish", "Anchovies", "Sardellen"),
    ("fish", "Shrimp", "Garnelen"),
    ("fish", "King Prawns", "Riesengarnelen"),
    ("fish", "Lobster", "Hummer"),
    ("fish", "Crab", "Krabbe"),
    ("fish", "Mussels", "Miesmuscheln"),
    ("fish", "Clams", "Venusmuscheln"),
    ("fish", "Oysters", "Austern"),
    ("fish", "Scallops", "Jakobsmuscheln"),
    ("fish", "Squid", "Tintenfisch"),
    ("fish", "Octopus", "Tintenfisch/Oktopus"),
    ("fish", "Crayfish", "Flusskrebs"),
    ("fish", "Fish Sticks", "Fischstäbchen"),
    ("fish", "Smoked Mackerel", "Räuchermakrele"),
    ("fish", "Swordfish", "Schwertfisch"),
    ("fish", "Halibut", "Heilbutt"),
    # Dairy & Eggs
    ("dairy_eggs", "Whole Milk", "Vollmilch"),
    ("dairy_eggs", "Skimmed Milk", "Magermilch"),
    ("dairy_eggs", "Semi-Skimmed Milk", "Halbfettmilch"),
    ("dairy_eggs", "Oat Milk", "Hafermilch"),
    ("dairy_eggs", "Almond Milk", "Mandelmilch"),
    ("dairy_eggs", "Soy Milk", "Sojamilch"),
    ("dairy_eggs", "Coconut Milk", "Kokosmilch"),
    ("dairy_eggs", "Organic Almond Milk", "Bio-Mandelmilch"),
    ("dairy_eggs", "Organic Soy Milk", "Bio-Sojamilch"),
    ("dairy_eggs", "Butter", "Butter"),
    ("dairy_eggs", "Margarine", "Margarine"),
    ("dairy_eggs", "Heavy Cream", "Sahne"),
    ("dairy_eggs", "Sour Cream", "Saure Sahne"),
    ("dairy_eggs", "Crème Fraîche", "Crème Fraîche"),
    ("dairy_eggs", "Cream Cheese", "Frischkäse"),
    ("dairy_eggs", "Cheddar", "Cheddar"),
    ("dairy_eggs", "Gouda", "Gouda"),
    ("dairy_eggs", "Edam", "Edamer"),
    ("dairy_eggs", "Emmental", "Emmentaler"),
    ("dairy_eggs", "Brie", "Brie"),
    ("dairy_eggs", "Camembert", "Camembert"),
    ("dairy_eggs", "Mozzarella", "Mozzarella"),
    ("dairy_eggs", "Parmesan", "Parmesan"),
    ("dairy_eggs", "Feta", "Feta"),
    ("dairy_eggs", "Ricotta", "Ricotta"),
    ("dairy_eggs", "Cottage Cheese", "Hüttenkäse"),
    ("dairy_eggs", "Greek Yogurt", "Griechischer Joghurt"),
    ("dairy_eggs", "Plain Yogurt", "Naturjoghurt"),
    ("dairy_eggs", "Flavored Yogurt", "Fruchtjoghurt"),
    ("dairy_eggs", "Kefir", "Kefir"),
    ("dairy_eggs", "Quark", "Quark"),
    ("dairy_eggs", "Eggs", "Eier"),
    ("dairy_eggs", "Free Range Eggs", "Freilandeier"),
    ("dairy_eggs", "Organic Eggs", "Bio-Eier"),
    ("dairy_eggs", "Condensed Milk", "Kondensmilch"),
    ("dairy_eggs", "Evaporated Milk", "Verdampfte Milch"),
    ("dairy_eggs", "Whipping Cream", "Schlagsahne"),
    ("dairy_eggs", "Buttermilk", "Buttermilch"),
    ("dairy_eggs", "Mascarpone", "Mascarpone"),
    ("dairy_eggs", "Aged Gouda", "Alter Gouda"),
    ("dairy_eggs", "Gruyère", "Gruyère"),
    ("dairy_eggs", "Blue Cheese", "Blauschimmelkäse"),
    # Bakery
    ("bakery", "White Bread", "Weißbrot"),
    ("bakery", "Whole Wheat Bread", "Vollkornbrot"),
    ("bakery", "Sourdough Bread", "Sauerteigbrot"),
    ("bakery", "Rye Bread", "Roggenbrot"),
    ("bakery", "Baguette", "Baguette"),
    ("bakery", "Ciabatta", "Ciabatta"),
    ("bakery", "Focaccia", "Focaccia"),
    ("bakery", "Pita Bread", "Pitabrot"),
    ("bakery", "Tortilla", "Tortilla"),
    ("bakery", "Naan Bread", "Nan-Brot"),
    ("bakery", "Bagel", "Bagel"),
    ("bakery", "English Muffin", "English Muffin"),
    ("bakery", "Croissant", "Croissant"),
    ("bakery", "Brioche", "Brioche"),
    ("bakery", "Burger Buns", "Burgerbrötchen"),
    ("bakery", "Hot Dog Buns", "Hotdog-Brötchen"),
    ("bakery", "Breadsticks", "Grissini"),
    ("bakery", "Muffin", "Muffin"),
    ("bakery", "Brownie", "Brownie"),
    ("bakery", "Cake", "Kuchen"),
    ("bakery", "Cheesecake", "Käsekuchen"),
    ("bakery", "Donut", "Donut"),
    ("bakery", "Danish Pastry", "Dänisches Gebäck"),
    ("bakery", "Cinnamon Roll", "Zimtschnecke"),
    ("bakery", "Pretzel", "Brezel"),
    ("bakery", "Crackers", "Knäckebrot"),
    ("bakery", "Rice Cakes", "Reiswaffeln"),
    ("bakery", "Flatbread", "Fladenbrot"),
    ("bakery", "Pumpernickel", "Pumpernickel"),
    ("bakery", "Spelt Bread", "Dinkelbrot"),
    # Baking Ingredients
    ("baking_ingredients", "All-Purpose Flour", "Weizenmehl"),
    ("baking_ingredients", "Whole Wheat Flour", "Vollkornmehl"),
    ("baking_ingredients", "Bread Flour", "Brotmehl"),
    ("baking_ingredients", "Almond Flour", "Mandelmehl"),
    ("baking_ingredients", "Coconut Flour", "Kokosmehl"),
    ("baking_ingredients", "Chickpea Flour", "Kichererbsenmehl"),
    ("baking_ingredients", "Cornstarch", "Stärkemehl"),
    ("baking_ingredients", "Baking Powder", "Backpulver"),
    ("baking_ingredients", "Baking Soda", "Natron"),
    ("baking_ingredients", "Yeast", "Hefe"),
    ("baking_ingredients", "Sugar", "Zucker"),
    ("baking_ingredients", "Brown Sugar", "Brauner Zucker"),
    ("baking_ingredients", "Powdered Sugar", "Puderzucker"),
    ("baking_ingredients", "Maple Syrup", "Ahornsirup"),
    ("baking_ingredients", "Agave Syrup", "Agavensirup"),
    ("baking_ingredients", "Vanilla Extract", "Vanilleextrakt"),
    ("baking_ingredients", "Cocoa Powder", "Kakaopulver"),
    ("baking_ingredients", "Dark Chocolate", "Zartbitterschokolade"),
    ("baking_ingredients", "Organic Dark Chocolate", "Bio-Zartbitterschokolade"),
    ("baking_ingredients", "Organic Maple Syrup", "Bio-Ahornsirup"),
    ("baking_ingredients", "Plantain Flour", "Kochbananenmehl"),
    ("baking_ingredients", "Tapioca Starch", "Tapiokastärke"),
    ("baking_ingredients", "Cassava Flour", "Maniokmehl"),
    ("baking_ingredients", "Rose Water", "Rosenwasser"),
    # Dry Goods
    ("dry_goods", "White Rice", "Weißer Reis"),
    ("dry_goods", "Brown Rice", "Brauner Reis"),
    ("dry_goods", "Basmati Rice", "Basmatireis"),
    ("dry_goods", "Jasmine Rice", "Jasminreis"),
    ("dry_goods", "Arborio Rice", "Arborio-Reis"),
    ("dry_goods", "Spaghetti", "Spaghetti"),
    ("dry_goods", "Penne", "Penne"),
    ("dry_goods", "Fusilli", "Fusilli"),
    ("dry_goods", "Rigatoni", "Rigatoni"),
    ("dry_goods", "Tagliatelle", "Tagliatelle"),
    ("dry_goods", "Lasagne Sheets", "Lasagneblätter"),
    ("dry_goods", "Egg Noodles", "Eiernudeln"),
    ("dry_goods", "Rice Noodles", "Reisnudeln"),
    ("dry_goods", "Udon Noodles", "Udon-Nudeln"),
    ("dry_goods", "Quinoa", "Quinoa"),
    ("dry_goods", "Couscous", "Couscous"),
    ("dry_goods", "Bulgur", "Bulgur"),
    ("dry_goods", "Oats", "Haferflocken"),
    ("dry_goods", "Rolled Oats", "Zartblatt-Haferflocken"),
    ("dry_goods", "Cornmeal", "Maismehl"),
    ("dry_goods", "Polenta", "Polenta"),
    ("dry_goods", "Lentils", "Linsen"),
    ("dry_goods", "Red Lentils", "Rote Linsen"),
    ("dry_goods", "Chickpeas", "Kichererbsen"),
    ("dry_goods", "Black Beans", "Schwarze Bohnen"),
    ("dry_goods", "Kidney Beans", "Kidneybohnen"),
    ("dry_goods", "Cannellini Beans", "Cannellini-Bohnen"),
    ("dry_goods", "Salt", "Salz"),
    ("dry_goods", "Honey", "Honig"),
    ("dry_goods", "Peanut Butter", "Erdnussbutter"),
    ("dry_goods", "Almond Butter", "Mandelbutter"),
    ("dry_goods", "Jam", "Marmelade"),
    ("dry_goods", "Strawberry Jam", "Erdbeermarmelade"),
    ("dry_goods", "Apricot Jam", "Aprikosenmarmelade"),
    ("dry_goods", "Nutella", "Nutella"),
    ("dry_goods", "Marmite", "Marmite"),
    ("dry_goods", "Nori Seaweed", "Nori-Algen"),
    ("dry_goods", "Panko Breadcrumbs", "Panko-Semmelbrösel"),
    ("dry_goods", "Wonton Wrappers", "Wan-Tan-Teigblätter"),
    ("dry_goods", "Spring Roll Wrappers", "Frühlingsrollenteigblätter"),
    ("dry_goods", "Rice Paper", "Reispapier"),
    ("dry_goods", "Organic Honey", "Bio-Honig"),
    ("dry_goods", "Organic Oats", "Bio-Haferflocken"),
    ("dry_goods", "Organic Quinoa", "Bio-Quinoa"),
    ("dry_goods", "Organic Granola", "Bio-Granola"),
    ("dry_goods", "Organic Lentils", "Bio-Linsen"),
    ("dry_goods", "Organic Chickpeas", "Bio-Kichererbsen"),
    ("dry_goods", "Organic Brown Rice", "Bio-Brauner Reis"),
    ("dry_goods", "Organic Pasta", "Bio-Nudeln"),
    ("dry_goods", "Organic Peanut Butter", "Bio-Erdnussbutter"),
    ("dry_goods", "Organic Tofu", "Bio-Tofu"),
    ("dry_goods", "Organic Tempeh", "Bio-Tempeh"),
    # Canned & Jarred Goods
    ("canned_goods", "Canned Tomatoes", "Dosentomaten"),
    ("canned_goods", "Tomato Paste", "Tomatenmark"),
    ("canned_goods", "Coconut Cream", "Kokosnusscreme"),
    ("canned_goods", "Vegetable Broth", "Gemüsebrühe"),
    ("canned_goods", "Chicken Broth", "Hühnerbrühe"),
    ("canned_goods", "Beef Broth", "Rinderbrühe"),
    ("canned_goods", "Canned Chickpeas", "Kichererbsen aus der Dose"),
    ("canned_goods", "Canned Lentils", "Linsen aus der Dose"),
    ("canned_goods", "Canned Corn", "Mais aus der Dose"),
    ("canned_goods", "Lentil Soup", "Linsensuppe"),
    # Frozen Foods
    ("frozen_foods", "Frozen Peas", "Tiefkühl-Erbsen"),
    ("frozen_foods", "Frozen Corn", "Tiefkühl-Mais"),
    ("frozen_foods", "Frozen Spinach", "Tiefkühl-Spinat"),
    ("frozen_foods", "Frozen Broccoli", "Tiefkühl-Brokkoli"),
    ("frozen_foods", "Frozen Mixed Vegetables", "Tiefkühl-Gemüsemischung"),
    ("frozen_foods", "Frozen Edamame", "Tiefkühl-Edamame"),
    ("frozen_foods", "Frozen Berries", "Tiefkühl-Beeren"),
    ("frozen_foods", "Frozen Strawberries", "Tiefkühl-Erdbeeren"),
    ("frozen_foods", "Frozen Mango", "Tiefkühl-Mango"),
    ("frozen_foods", "Frozen Pizza", "Tiefkühl-Pizza"),
    ("frozen_foods", "Frozen Lasagne", "Tiefkühl-Lasagne"),
    ("frozen_foods", "Frozen Burger Patties", "Tiefkühl-Burgerpatties"),
    ("frozen_foods", "Frozen Chicken Nuggets", "Tiefkühl-Chicken Nuggets"),
    ("frozen_foods", "Frozen Fish Fillet", "Tiefkühl-Fischfilet"),
    ("frozen_foods", "Frozen Shrimp", "Tiefkühl-Garnelen"),
    ("frozen_foods", "Frozen Fries", "Tiefkühl-Pommes"),
    ("frozen_foods", "Frozen Waffles", "Tiefkühl-Waffeln"),
    ("frozen_foods", "Frozen Pancakes", "Tiefkühl-Pfannkuchen"),
    ("frozen_foods", "Ice Cream Vanilla", "Vanilleeis"),
    ("frozen_foods", "Ice Cream Chocolate", "Schokoladeneis"),
    ("frozen_foods", "Ice Cream Strawberry", "Erdbeereis"),
    ("frozen_foods", "Sorbet", "Sorbet"),
    ("frozen_foods", "Frozen Dumplings", "Tiefkühl-Teigtaschen"),
    ("frozen_foods", "Frozen Spring Rolls", "Tiefkühl-Frühlingsrollen"),
    ("frozen_foods", "Frozen Pierogi", "Tiefkühl-Pierogi"),
    ("frozen_foods", "Frozen Burrito", "Tiefkühl-Burrito"),
    ("frozen_foods", "Frozen Pot Pie", "Tiefkühl-Fleischpastete"),
    ("frozen_foods", "Frozen Soup", "Tiefkühl-Suppe"),
    ("frozen_foods", "Frozen Bread Dough", "Tiefkühl-Brotteig"),
    ("frozen_foods", "Frozen Hash Browns", "Tiefkühl-Hash Browns"),
    # Beverages
    ("beverages", "Still Water", "Stilles Wasser"),
    ("beverages", "Sparkling Water", "Mineralwasser"),
    ("beverages", "Orange Juice", "Orangensaft"),
    ("beverages", "Apple Juice", "Apfelsaft"),
    ("beverages", "Grape Juice", "Traubensaft"),
    ("beverages", "Tomato Juice", "Tomatensaft"),
    ("beverages", "Lemonade", "Limonade"),
    ("beverages", "Cola", "Cola"),
    ("beverages", "Diet Cola", "Cola light"),
    ("beverages", "Sparkling Lemon", "Zitronenlimonade"),
    ("beverages", "Energy Drink", "Energydrink"),
    ("beverages", "Iced Tea", "Eistee"),
    ("beverages", "Protein Shake", "Proteinshake"),
    ("beverages", "Smoothie", "Smoothie"),
    ("beverages", "Coconut Water", "Kokoswasser"),
    ("beverages", "Kombucha", "Kombucha"),
    ("beverages", "Vegetable Juice", "Gemüsesaft"),
    ("beverages", "Cranberry Juice", "Cranberrysaft"),
    # Coffee & Tea
    ("coffee_tea", "Green Tea", "Grüner Tee"),
    ("coffee_tea", "Black Tea", "Schwarzer Tee"),
    ("coffee_tea", "Herbal Tea", "Kräutertee"),
    ("coffee_tea", "Chamomile Tea", "Kamillentee"),
    ("coffee_tea", "Peppermint Tea", "Pfefferminztee"),
    ("coffee_tea", "Coffee Beans", "Kaffeebohnen"),
    ("coffee_tea", "Ground Coffee", "Gemahlener Kaffee"),
    ("coffee_tea", "Instant Coffee", "Instantkaffee"),
    ("coffee_tea", "Espresso Pods", "Espresso-Kapseln"),
    ("coffee_tea", "Hot Chocolate", "Heiße Schokolade"),
    ("coffee_tea", "Organic Green Tea", "Bio-Grüntee"),
    ("coffee_tea", "Organic Herbal Tea", "Bio-Kräutertee"),
    # Snacks & Sweets
    ("snacks_sweets", "Potato Chips", "Kartoffelchips"),
    ("snacks_sweets", "Tortilla Chips", "Tortillachips"),
    ("snacks_sweets", "Popcorn", "Popcorn"),
    ("snacks_sweets", "Pretzels", "Brezel-Snacks"),
    ("snacks_sweets", "Rice Crackers", "Reiscracker"),
    ("snacks_sweets", "Peanuts", "Erdnüsse"),
    ("snacks_sweets", "Cashews", "Cashewnüsse"),
    ("snacks_sweets", "Almonds", "Mandeln"),
    ("snacks_sweets", "Walnuts", "Walnüsse"),
    ("snacks_sweets", "Trail Mix", "Nussmischung"),
    ("snacks_sweets", "Granola Bar", "Müsliriegel"),
    ("snacks_sweets", "Protein Bar", "Proteinriegel"),
    ("snacks_sweets", "Cereal Bar", "Getreideriegel"),
    ("snacks_sweets", "Gummy Bears", "Gummibären"),
    ("snacks_sweets", "Chocolate Bar", "Schokoriegel"),
    ("snacks_sweets", "Kit Kat", "Kit Kat"),
    ("snacks_sweets", "Snickers", "Snickers"),
    ("snacks_sweets", "Twix", "Twix"),
    ("snacks_sweets", "Oreo", "Oreo"),
    ("snacks_sweets", "Digestive Biscuits", "Digestive Kekse"),
    ("snacks_sweets", "Shortbread", "Shortbread"),
    ("snacks_sweets", "Wafer", "Waffelgebäck"),
    ("snacks_sweets", "Candy", "Bonbons"),
    ("snacks_sweets", "Lollipop", "Lutscher"),
    ("snacks_sweets", "Chewing Gum", "Kaugummi"),
    ("snacks_sweets", "Fruit Gummies", "Fruchtgummi"),
    ("snacks_sweets", "Jelly Beans", "Jelly Beans"),
    ("snacks_sweets", "Marshmallow", "Marshmallow"),
    ("snacks_sweets", "Dark Chocolate Squares", "Zartbitterschokolade-Stücke"),
    ("snacks_sweets", "Mints", "Pfefferminzdrops"),
    ("snacks_sweets", "Beef Jerky", "Beef Jerky"),
    ("snacks_sweets", "Dried Mango", "Getrocknete Mango"),
    ("snacks_sweets", "Dried Cranberries", "Getrocknete Cranberries"),
    ("snacks_sweets", "Sunflower Seeds", "Sonnenblumenkerne"),
    ("snacks_sweets", "Pumpkin Seeds", "Kürbiskerne"),
    ("snacks_sweets", "Sesame Snaps", "Sesam-Snaps"),
    ("snacks_sweets", "Milk Chocolate", "Vollmilchschokolade"),
    ("snacks_sweets", "Organic Almonds", "Bio-Mandeln"),
    # Condiments, Sauces & Oils
    ("condiments_spices", "Ketchup", "Ketchup"),
    ("condiments_spices", "Mustard", "Senf"),
    ("condiments_spices", "Dijon Mustard", "Dijon-Senf"),
    ("condiments_spices", "Mayonnaise", "Mayonnaise"),
    ("condiments_spices", "Barbecue Sauce", "Barbecue-Soße"),
    ("condiments_spices", "Hot Sauce", "Scharfe Soße"),
    ("condiments_spices", "Sriracha", "Sriracha"),
    ("condiments_spices", "Tabasco", "Tabasco"),
    ("condiments_spices", "Teriyaki Sauce", "Teriyaki-Soße"),
    ("condiments_spices", "Hoisin Sauce", "Hoisin-Soße"),
    ("condiments_spices", "Fish Sauce", "Fischsoße"),
    ("condiments_spices", "Oyster Sauce", "Austernsoße"),
    ("condiments_spices", "Sweet Chili Sauce", "Süß-Chili-Soße"),
    ("condiments_spices", "Pesto", "Pesto"),
    ("condiments_spices", "Hummus", "Hummus"),
    ("condiments_spices", "Guacamole", "Guacamole"),
    ("condiments_spices", "Salsa", "Salsa"),
    ("condiments_spices", "Ranch Dressing", "Ranch-Dressing"),
    ("condiments_spices", "Caesar Dressing", "Caesar-Dressing"),
    ("condiments_spices", "Italian Dressing", "Italienisches Dressing"),
    ("condiments_spices", "Black Pepper", "Schwarzer Pfeffer"),
    ("condiments_spices", "White Pepper", "Weißer Pfeffer"),
    ("condiments_spices", "Paprika Powder", "Paprikapulver"),
    ("condiments_spices", "Cayenne Pepper", "Cayennepfeffer"),
    ("condiments_spices", "Cumin", "Kreuzkümmel"),
    ("condiments_spices", "Coriander Seeds", "Koriandersamen"),
    ("condiments_spices", "Cinnamon", "Zimt"),
    ("condiments_spices", "Nutmeg", "Muskatnuss"),
    ("condiments_spices", "Cloves", "Nelken"),
    ("condiments_spices", "Cardamom", "Kardamom"),
    ("condiments_spices", "Turmeric Powder", "Kurkumapulver"),
    ("condiments_spices", "Curry Powder", "Currypulver"),
    ("condiments_spices", "Garam Masala", "Garam Masala"),
    ("condiments_spices", "Bay Leaves", "Lorbeerblätter"),
    ("condiments_spices", "Oregano", "Oregano"),
    ("condiments_spices", "Basil Dried", "Getrocknetes Basilikum"),
    ("condiments_spices", "Thyme Dried", "Getrockneter Thymian"),
    ("condiments_spices", "Chili Flakes", "Chiliflocken"),
    ("condiments_spices", "Garlic Powder", "Knoblauchpulver"),
    ("condiments_spices", "Onion Powder", "Zwiebelpulver"),
    ("condiments_spices", "Smoked Paprika", "Geräuchertes Paprikapulver"),
    ("condiments_spices", "Vanilla Bean", "Vanilleschote"),
    ("condiments_spices", "Star Anise", "Sternanis"),
    ("condiments_spices", "Saffron", "Safran"),
    ("condiments_spices", "Capers", "Kapern"),
    ("condiments_spices", "Pickles", "Gewürzgurken"),
    ("condiments_spices", "Olives", "Oliven"),
    ("condiments_spices", "Sun-Dried Tomatoes", "Getrocknete Tomaten"),
    ("condiments_spices", "Olive Oil", "Olivenöl"),
    ("condiments_spices", "Sunflower Oil", "Sonnenblumenöl"),
    ("condiments_spices", "Coconut Oil", "Kokosöl"),
    ("condiments_spices", "Canola Oil", "Rapsöl"),
    ("condiments_spices", "Sesame Oil", "Sesamöl"),
    ("condiments_spices", "Apple Cider Vinegar", "Apfelessig"),
    ("condiments_spices", "White Wine Vinegar", "Weißweinessig"),
    ("condiments_spices", "Balsamic Vinegar", "Balsamico-Essig"),
    ("condiments_spices", "Soy Sauce", "Sojasoße"),
    ("condiments_spices", "Worcestershire Sauce", "Worcestershire Sauce"),
    ("condiments_spices", "Tahini", "Tahini"),
    ("condiments_spices", "Organic Olive Oil", "Bio-Olivenöl"),
    ("condiments_spices", "Organic Coconut Oil", "Bio-Kokosöl"),
    ("condiments_spices", "Miso Paste", "Misopaste"),
    ("condiments_spices", "Kimchi", "Kimchi"),
    ("condiments_spices", "Coconut Aminos", "Kokosaminos"),
    ("condiments_spices", "Gochujang", "Gochujang"),
    ("condiments_spices", "Curry Paste", "Currypaste"),
    ("condiments_spices", "Red Curry Paste", "Rote Currypaste"),
    ("condiments_spices", "Green Curry Paste", "Grüne Currypaste"),
    ("condiments_spices", "Harissa", "Harissa"),
    ("condiments_spices", "Za'atar", "Za'atar"),
    ("condiments_spices", "Sumac", "Sumach"),
    ("condiments_spices", "Preserved Lemons", "Eingelegte Zitronen"),
    ("condiments_spices", "Dashi Stock", "Dashi-Brühe"),
    ("condiments_spices", "Mirin", "Mirin"),
    ("condiments_spices", "Ponzu Sauce", "Ponzu-Soße"),
    ("condiments_spices", "Black Bean Sauce", "Schwarzbohnensauce"),
    ("condiments_spices", "Satay Sauce", "Satay-Soße"),
    ("condiments_spices", "Coconut Vinegar", "Kokosnussessig"),
    # Health
    ("health", "Bandages", "Pflaster"),
    ("health", "Paracetamol", "Paracetamol"),
    ("health", "Ibuprofen", "Ibuprofen"),
    ("health", "Vitamins", "Vitamine"),
    ("health", "Vitamin C", "Vitamin C"),
    ("health", "Multivitamin", "Multivitamin"),
    ("health", "Protein Powder", "Proteinpulver"),
    ("health", "Fish Oil", "Fischöl"),
    ("health", "Collagen Supplements", "Kollagenpräparate"),
    # Cosmetics & Hygiene
    ("cosmetics_hygiene", "Toothpaste", "Zahnpasta"),
    ("cosmetics_hygiene", "Toothbrush", "Zahnbürste"),
    ("cosmetics_hygiene", "Dental Floss", "Zahnseide"),
    ("cosmetics_hygiene", "Mouthwash", "Mundspülung"),
    ("cosmetics_hygiene", "Shampoo", "Shampoo"),
    ("cosmetics_hygiene", "Conditioner", "Haarspülung"),
    ("cosmetics_hygiene", "Body Wash", "Duschgel"),
    ("cosmetics_hygiene", "Bar Soap", "Seife"),
    ("cosmetics_hygiene", "Face Wash", "Gesichtsreinigung"),
    ("cosmetics_hygiene", "Moisturizer", "Feuchtigkeitscreme"),
    ("cosmetics_hygiene", "Sunscreen", "Sonnencreme"),
    ("cosmetics_hygiene", "Lip Balm", "Lippenbalsam"),
    ("cosmetics_hygiene", "Deodorant", "Deodorant"),
    ("cosmetics_hygiene", "Antiperspirant", "Antitranspirant"),
    ("cosmetics_hygiene", "Razor", "Rasierer"),
    ("cosmetics_hygiene", "Shaving Cream", "Rasiercreme"),
    ("cosmetics_hygiene", "Aftershave", "Aftershave"),
    ("cosmetics_hygiene", "Hand Cream", "Handcreme"),
    ("cosmetics_hygiene", "Nail Clippers", "Nagelschere"),
    ("cosmetics_hygiene", "Cotton Pads", "Wattepads"),
    ("cosmetics_hygiene", "Cotton Buds", "Wattestäbchen"),
    # Cleaning & Laundry
    ("cleaning_laundry", "Dish Soap", "Spülmittel"),
    ("cleaning_laundry", "Dishwasher Tablets", "Geschirrspültabs"),
    ("cleaning_laundry", "Dishwasher Powder", "Geschirrspülpulver"),
    ("cleaning_laundry", "Laundry Detergent", "Waschmittel"),
    ("cleaning_laundry", "Fabric Softener", "Weichspüler"),
    ("cleaning_laundry", "Stain Remover", "Fleckenentferner"),
    ("cleaning_laundry", "All-Purpose Cleaner", "Allzweckreiniger"),
    ("cleaning_laundry", "Bathroom Cleaner", "Badreiniger"),
    ("cleaning_laundry", "Toilet Cleaner", "WC-Reiniger"),
    ("cleaning_laundry", "Floor Cleaner", "Bodenreiniger"),
    ("cleaning_laundry", "Glass Cleaner", "Glasreiniger"),
    ("cleaning_laundry", "Oven Cleaner", "Ofenreiniger"),
    ("cleaning_laundry", "Bleach", "Bleichmittel"),
    ("cleaning_laundry", "Sponge", "Schwamm"),
    ("cleaning_laundry", "Scrubbing Brush", "Scheuerbürste"),
    ("cleaning_laundry", "Mop", "Wischmopp"),
    # Home & Garden
    ("home_garden", "Paper Towels", "Küchenpapier"),
    ("home_garden", "Toilet Paper", "Toilettenpapier"),
    ("home_garden", "Trash Bags", "Müllbeutel"),
    ("home_garden", "Zip Lock Bags", "Gefrierbeutel"),
    ("home_garden", "Aluminum Foil", "Aluminiumfolie"),
    ("home_garden", "Plastic Wrap", "Frischhaltefolie"),
    ("home_garden", "Baking Paper", "Backpapier"),
    ("home_garden", "Broom", "Besen"),
    ("home_garden", "Dustpan", "Kehrschaufel"),
    ("home_garden", "Air Freshener", "Raumduft"),
    ("home_garden", "Candle", "Kerze"),
    ("home_garden", "Matches", "Streichhölzer"),
    # Electronics
    ("electronics", "Batteries", "Batterien"),
    ("electronics", "Light Bulbs", "Glühbirnen"),
    # Baby
    ("baby", "Baby Food Purée", "Babybreipüree"),
    ("baby", "Baby Cereal", "Babybrei"),
    ("baby", "Baby Formula", "Säuglingsnahrung"),
    ("baby", "Baby Snacks", "Babysnacks"),
    ("baby", "Baby Juice", "Babysaft"),
    ("baby", "Diapers", "Windeln"),
    ("baby", "Baby Wipes", "Babyfeuchttücher"),
    ("baby", "Baby Shampoo", "Babyshampoo"),
    ("baby", "Baby Lotion", "Babylotion"),
    ("baby", "Baby Oil", "Babyöl"),
    ("baby", "Baby Powder", "Babypuder"),
    ("baby", "Baby Toothbrush", "Babyzahnbürste"),
    ("baby", "Pacifier", "Schnuller"),
    ("baby", "Baby Bottle", "Babyflasche"),
    ("baby", "Teether", "Beißring"),
    ("baby", "Diaper Rash Cream", "Wundschutzcreme"),
    # Pets
    ("pets", "Dry Dog Food", "Trockenfutter für Hunde"),
    ("pets", "Wet Dog Food", "Nassfutter für Hunde"),
    ("pets", "Dog Treats", "Hundekekse"),
    ("pets", "Dry Cat Food", "Trockenfutter für Katzen"),
    ("pets", "Wet Cat Food", "Nassfutter für Katzen"),
    ("pets", "Cat Treats", "Katzensnacks"),
    ("pets", "Cat Litter", "Katzenstreu"),
    ("pets", "Bird Food", "Vogelfutter"),
    ("pets", "Fish Food", "Fischfutter"),
    ("pets", "Hamster Food", "Hamsterfutter"),
    ("pets", "Rabbit Pellets", "Kaninchenpellets"),
    ("pets", "Pet Shampoo", "Tiershampoo"),
    ("pets", "Flea Treatment", "Flohbehandlung"),
    ("pets", "Dog Poop Bags", "Hundekotbeutel"),
    ("pets", "Pet Vitamins", "Tiervitamine"),
    # Ready Meals
    ("ready_meals", "Tzatziki", "Tzatziki"),
    ("ready_meals", "Ready Meal Pasta", "Fertiggericht Pasta"),
    ("ready_meals", "Ready Meal Curry", "Fertiggericht Curry"),
    ("ready_meals", "Soup Cup", "Suppenbecher"),
    ("ready_meals", "Sushi", "Sushi"),
    ("ready_meals", "Sandwich", "Sandwich"),
    ("ready_meals", "Wrap", "Wrap"),
    ("ready_meals", "Quiche", "Quiche"),
    ("ready_meals", "Rotisserie Chicken", "Brathähnchen"),
    ("ready_meals", "Cooked Ham", "Gekochter Schinken"),
    ("ready_meals", "Smoked Turkey", "Geräucherter Truthahn"),
    ("ready_meals", "Roast Beef Slices", "Roastbeefscheiben"),
    ("ready_meals", "Pastrami", "Pastrami"),
    ("ready_meals", "Mortadella", "Mortadella"),
    ("ready_meals", "Pepperoni", "Pepperoni"),
    ("ready_meals", "Liverwurst", "Leberwurst"),
    ("ready_meals", "Potato Salad", "Kartoffelsalat"),
    ("ready_meals", "Coleslaw", "Coleslaw"),
    ("ready_meals", "Tabouli", "Taboulé"),
    # Alcohol
    ("alcohol", "Lager Beer", "Lagerbier"),
    ("alcohol", "Craft Beer", "Craftbier"),
    ("alcohol", "Wheat Beer", "Weizenbier"),
    ("alcohol", "Dark Beer", "Dunkles Bier"),
    ("alcohol", "Non-Alcoholic Beer", "Alkoholfreies Bier"),
    ("alcohol", "White Wine", "Weißwein"),
    ("alcohol", "Red Wine", "Rotwein"),
    ("alcohol", "Rosé Wine", "Roséwein"),
    ("alcohol", "Sparkling Wine", "Sekt"),
    ("alcohol", "Champagne", "Champagner"),
    ("alcohol", "Prosecco", "Prosecco"),
    ("alcohol", "Vodka", "Wodka"),
    ("alcohol", "Gin", "Gin"),
    ("alcohol", "Rum", "Rum"),
    ("alcohol", "Whisky", "Whisky"),
    ("alcohol", "Tequila", "Tequila"),
    ("alcohol", "Brandy", "Weinbrand"),
    ("alcohol", "Liqueur", "Likör"),
    ("alcohol", "Aperol", "Aperol"),
    ("alcohol", "Vermouth", "Wermut"),
    ("alcohol", "Cider", "Apfelwein"),
    ("alcohol", "Hard Seltzer", "Hard Seltzer"),
    ("alcohol", "Sake", "Sake"),
    ("alcohol", "Mead", "Met"),
]


def _build_brand_products():
    """Generate common German supermarket brand+product combinations."""

    # (category_key, [brands], [(en_name, de_name), ...])
    brand_templates = [
        (
            "snacks_sweets",
            ["Milka", "Ritter Sport", "Haribo", "Kinder", "Ferrero"],
            [
                ("Milk Chocolate", "Vollmilchschokolade"),
                ("Dark Chocolate", "Zartbitterschokolade"),
                ("Hazelnut Chocolate", "Haselnussschokolade"),
                ("Chocolate Biscuit", "Schokokeks"),
                ("Chocolate Bar", "Schokoriegel"),
                ("Wafer", "Waffelgebäck"),
                ("Gummy Bears", "Fruchtgummi"),
                ("Yogurt Chocolate", "Joghurtschokolade"),
                ("Chocolate Spread", "Schokocreme"),
                ("Cookie", "Keks"),
            ],
        ),
        (
            "dairy_eggs",
            ["Müller", "Ehrmann", "Danone", "Zott", "Weihenstephan", "Alpro", "MinusL", "Arla"],
            [
                ("Yogurt", "Joghurt"),
                ("Strawberry Yogurt", "Erdbeerjoghurt"),
                ("Vanilla Yogurt", "Vanillejoghurt"),
                ("Quark", "Quark"),
                ("Milk", "Milch"),
                ("Whole Milk", "Vollmilch"),
                ("Cream Cheese", "Frischkäse"),
                ("Butter", "Butter"),
                ("Pudding", "Pudding"),
                ("Kefir", "Kefir"),
            ],
        ),
        (
            "beverages",
            [
                "Coca-Cola",
                "Fanta",
                "Sprite",
                "Mezzo Mix",
                "Red Bull",
                "Gerolsteiner",
                "Volvic",
                "Vio",
            ],
            [
                ("Still Water", "Stilles Wasser"),
                ("Sparkling Water", "Mineralwasser"),
                ("Cola", "Cola"),
                ("Lemonade", "Limonade"),
                ("Orange Soda", "Orangenlimonade"),
                ("Iced Tea", "Eistee"),
                ("Energy Drink", "Energydrink"),
                ("Apple Spritzer", "Apfelschorle"),
            ],
        ),
        (
            "dry_goods",
            ["Barilla", "Birkel", "Knorr", "Maggi", "Ben's Original", "Müller's Mühle", "KoRo", "Alnatura"],
            [
                ("Spaghetti", "Spaghetti"),
                ("Penne", "Penne"),
                ("Fusilli", "Fusilli"),
                ("Rice", "Reis"),
                ("Basmati Rice", "Basmatireis"),
                ("Lentils", "Linsen"),
                ("Chickpeas", "Kichererbsen"),
                ("Oats", "Haferflocken"),
                ("Couscous", "Couscous"),
                ("Tomato Soup", "Tomatensuppe"),
            ],
        ),
        (
            "condiments_spices",
            ["Thomy", "Hela", "Kühne", "Hengstenberg", "Develey", "Heinz", "Kikkoman", "Byodo"],
            [
                ("Ketchup", "Ketchup"),
                ("Mustard", "Senf"),
                ("Mayonnaise", "Mayonnaise"),
                ("Barbecue Sauce", "Barbecue-Soße"),
                ("Soy Sauce", "Sojasoße"),
                ("Pesto", "Pesto"),
                ("Olive Oil", "Olivenöl"),
                ("Pickles", "Gewürzgurken"),
                ("Hot Sauce", "Scharfe Soße"),
                ("Salad Dressing", "Salatdressing"),
            ],
        ),
        (
            "frozen_foods",
            ["Iglo", "Frosta", "Dr. Oetker", "Wagner", "Coppenrath & Wiese", "Eismann"],
            [
                ("Frozen Pizza", "Tiefkühl-Pizza"),
                ("Frozen Vegetables", "Tiefkühl-Gemüse"),
                ("Frozen Fish Fillet", "Tiefkühl-Fischfilet"),
                ("Frozen Fries", "Tiefkühl-Pommes"),
                ("Frozen Lasagne", "Tiefkühl-Lasagne"),
                ("Ice Cream", "Speiseeis"),
                ("Frozen Berries", "Tiefkühl-Beeren"),
                ("Frozen Spinach", "Tiefkühl-Spinat"),
            ],
        ),
        (
            "bakery",
            ["Harry", "Mestemacher", "Golden Toast", "Wasa", "Lieken"],
            [
                ("Whole Wheat Bread", "Vollkornbrot"),
                ("Toast Bread", "Toastbrot"),
                ("Rye Bread", "Roggenbrot"),
                ("Crispbread", "Knäckebrot"),
                ("Croissant", "Croissant"),
                ("Bagel", "Bagel"),
                ("Pretzel", "Brezel"),
                ("Bread Roll", "Brötchen"),
            ],
        ),
        (
            "meat",
            ["Rügenwalder", "Wilhelm Brandenburg", "Herta", "Gutfried", "Wiesenhof", "Block House"],
            [
                ("Salami", "Salami"),
                ("Ham", "Schinken"),
                ("Turkey Breast", "Putenbrust"),
                ("Chicken Breast", "Hähnchenbrust"),
                ("Sausage", "Wurst"),
                ("Bratwurst", "Bratwurst"),
                ("Minced Meat", "Hackfleisch"),
                ("Beef Steak", "Rindersteak"),
            ],
        ),
        (
            "ready_meals",
            ["Knorr", "Maggi", "Bofrost", "Youcook", "Bürger", "Bonduelle"],
            [
                ("Ready Meal Pasta", "Fertiggericht Pasta"),
                ("Ready Meal Curry", "Fertiggericht Curry"),
                ("Soup Cup", "Suppenbecher"),
                ("Potato Salad", "Kartoffelsalat"),
                ("Wrap", "Wrap"),
                ("Sandwich", "Sandwich"),
                ("Sushi", "Sushi"),
                ("Microwave Meal", "Mikrowellengericht"),
            ],
        ),
        (
            "cleaning_laundry",
            ["Persil", "Ariel", "Lenor", "Pril", "Frosch", "Bref", "Somat", "Vanish"],
            [
                ("Laundry Detergent", "Waschmittel"),
                ("Fabric Softener", "Weichspüler"),
                ("Dish Soap", "Spülmittel"),
                ("Dishwasher Tabs", "Geschirrspültabs"),
                ("Toilet Cleaner", "WC-Reiniger"),
                ("All-Purpose Cleaner", "Allzweckreiniger"),
                ("Stain Remover", "Fleckenentferner"),
                ("Glass Cleaner", "Glasreiniger"),
            ],
        ),
        (
            "coffee_tea",
            ["Jacobs", "Dallmayr", "Tchibo", "Lavazza", "Meßmer", "Teekanne", "Krüger"],
            [
                ("Coffee Beans", "Kaffeebohnen"),
                ("Ground Coffee", "Gemahlener Kaffee"),
                ("Instant Coffee", "Instantkaffee"),
                ("Espresso", "Espresso"),
                ("Black Tea", "Schwarzer Tee"),
                ("Herbal Tea", "Kräutertee"),
                ("Green Tea", "Grüner Tee"),
                ("Chai Tea", "Chai Tee"),
            ],
        ),
        (
            "baby",
            ["HiPP", "Aptamil", "Bebivita", "NUK", "Pampers"],
            [
                ("Baby Formula", "Säuglingsnahrung"),
                ("Baby Food", "Babybrei"),
                ("Baby Snacks", "Babysnacks"),
                ("Baby Wipes", "Babyfeuchttücher"),
                ("Diapers", "Windeln"),
                ("Baby Lotion", "Babylotion"),
                ("Pacifier", "Schnuller"),
                ("Baby Bottle", "Babyflasche"),
            ],
        ),
        (
            "pets",
            ["Pedigree", "Whiskas", "Felix", "Sheba", "Royal Canin", "Vitakraft"],
            [
                ("Dry Dog Food", "Trockenfutter für Hunde"),
                ("Wet Dog Food", "Nassfutter für Hunde"),
                ("Dog Treats", "Hundesnacks"),
                ("Dry Cat Food", "Trockenfutter für Katzen"),
                ("Wet Cat Food", "Nassfutter für Katzen"),
                ("Cat Treats", "Katzensnacks"),
                ("Cat Litter", "Katzenstreu"),
                ("Bird Food", "Vogelfutter"),
            ],
        ),
        (
            "cosmetics_hygiene",
            ["Nivea", "Balea", "Elmex", "Meridol", "Signal", "L'Oreal", "Neutrogena"],
            [
                ("Shampoo", "Shampoo"),
                ("Body Wash", "Duschgel"),
                ("Deodorant", "Deodorant"),
                ("Toothpaste", "Zahnpasta"),
                ("Toothbrush", "Zahnbürste"),
                ("Face Cream", "Gesichtscreme"),
                ("Hand Cream", "Handcreme"),
                ("Sunscreen", "Sonnencreme"),
            ],
        ),
        (
            "health",
            ["Doppelherz", "tetesept", "ratiopharm", "Abtei", "Orthomol"],
            [
                ("Vitamin C", "Vitamin C"),
                ("Multivitamin", "Multivitamin"),
                ("Magnesium", "Magnesium"),
                ("Ibuprofen", "Ibuprofen"),
                ("Paracetamol", "Paracetamol"),
                ("Electrolyte Powder", "Elektrolytpulver"),
                ("Protein Powder", "Proteinpulver"),
                ("Immune Support", "Immunsupport"),
            ],
        ),
    ]

    generated = []
    for category_key, brands, product_pairs in brand_templates:
        for brand in brands:
            for product_en, product_de in product_pairs:
                generated.append(
                    (
                        category_key,
                        f"{brand} {product_en}",
                        f"{brand} {product_de}",
                    )
                )
    return generated


MANUAL_BRAND_ALIASES = [
    # Explicit typo-like/common brand shorthand users might type.
    ("snacks_sweets", "Mika Milk Chocolate", "Mika Vollmilch"),
    ("snacks_sweets", "Milka Milk Chocolate", "Milka Vollmilch"),
    ("snacks_sweets", "Milka Yogurt Chocolate", "Milka Joghurtschokolade"),
    ("snacks_sweets", "Ritter Sport Chocolate", "Ritter Sport Schokolade"),
    ("dairy_eggs", "Müller Yogurt", "Müller Joghurt"),
]


STEM_PRODUCTS = [
    ("snacks_sweets", "Chocolate", "Schokolade"),
    ("dairy_eggs", "Yogurt", "Joghurt"),
    ("dairy_eggs", "Cheese", "Käse"),
    ("bakery", "Bread", "Brot"),
    ("meat", "Sausage", "Wurst"),
    ("fruits_vegetables", "Tomatoes", "Tomaten"),
    ("fruits_vegetables", "Potatoes", "Kartoffeln"),
    ("beverages", "Water", "Wasser"),
    ("coffee_tea", "Coffee", "Kaffee"),
    ("coffee_tea", "Tea", "Tee"),
]


PRODUCTS = BASE_PRODUCTS + _build_brand_products() + MANUAL_BRAND_ALIASES + STEM_PRODUCTS
if __name__ == "__main__":
    print(f"Categories: {len(CATEGORIES)}")
    print(f"Products: {len(PRODUCTS)}")
    print("Use `python3 generate_dart_catalog.py` to regenerate the offline catalog.")
