#!/usr/bin/env python3
import json

# Categories: key -> {en, de}
CATEGORIES = {
    "fruits_vegetables": {"en": "Fruits & Vegetables", "de": "Obst & Gemüse"},
    "meat":              {"en": "Meat", "de": "Fleisch"},
    "fish":              {"en": "Fish & Seafood", "de": "Fisch & Meeresfrüchte"},
    "dairy_eggs":        {"en": "Dairy & Eggs", "de": "Milchprodukte & Eier"},
    "bakery_bread":      {"en": "Bakery & Bread", "de": "Backwaren & Brot"},
    "pantry":            {"en": "Pantry & Dry Goods", "de": "Vorrat & Trockenwaren"},
    "frozen_foods":      {"en": "Frozen Foods", "de": "Tiefkühlkost"},
    "beverages":         {"en": "Beverages", "de": "Getränke"},
    "snacks_sweets":     {"en": "Snacks & Sweets", "de": "Snacks & Süßigkeiten"},
    "condiments_spices": {"en": "Condiments & Spices", "de": "Gewürze & Saucen"},
    "health_beauty":     {"en": "Health & Beauty", "de": "Gesundheit & Pflege"},
    "household_cleaning":{"en": "Household & Cleaning", "de": "Haushalt & Reinigung"},
    "baby_care":         {"en": "Baby Care", "de": "Babypflege"},
    "pets":              {"en": "Pets", "de": "Haustierbedarf"},
    "deli_prepared":     {"en": "Deli & Prepared Foods", "de": "Feinkost & Fertiggerichte"},
    "alcohol":           {"en": "Alcohol", "de": "Alkohol"},
    "organic":           {"en": "Organic & Natural", "de": "Bio & Natürlich"},
    "international":     {"en": "International Foods", "de": "Internationale Küche"},
}

# Products: list of (category_key, en_name, de_name)
PRODUCTS = [
    # Fruits & Vegetables
    ("fruits_vegetables","Apple","Apfel"),
    ("fruits_vegetables","Banana","Banane"),
    ("fruits_vegetables","Orange","Orange"),
    ("fruits_vegetables","Mango","Mango"),
    ("fruits_vegetables","Pineapple","Ananas"),
    ("fruits_vegetables","Strawberry","Erdbeere"),
    ("fruits_vegetables","Blueberry","Heidelbeere"),
    ("fruits_vegetables","Raspberry","Himbeere"),
    ("fruits_vegetables","Blackberry","Brombeere"),
    ("fruits_vegetables","Grapes","Weintrauben"),
    ("fruits_vegetables","Watermelon","Wassermelone"),
    ("fruits_vegetables","Cantaloupe","Cantaloupe-Melone"),
    ("fruits_vegetables","Peach","Pfirsich"),
    ("fruits_vegetables","Pear","Birne"),
    ("fruits_vegetables","Plum","Pflaume"),
    ("fruits_vegetables","Cherry","Kirsche"),
    ("fruits_vegetables","Apricot","Aprikose"),
    ("fruits_vegetables","Kiwi","Kiwi"),
    ("fruits_vegetables","Papaya","Papaya"),
    ("fruits_vegetables","Pomegranate","Granatapfel"),
    ("fruits_vegetables","Lemon","Zitrone"),
    ("fruits_vegetables","Lime","Limette"),
    ("fruits_vegetables","Grapefruit","Grapefruit"),
    ("fruits_vegetables","Coconut","Kokosnuss"),
    ("fruits_vegetables","Avocado","Avocado"),
    ("fruits_vegetables","Tomato","Tomate"),
    ("fruits_vegetables","Cherry Tomato","Cocktailtomate"),
    ("fruits_vegetables","Cucumber","Gurke"),
    ("fruits_vegetables","Bell Pepper","Paprika"),
    ("fruits_vegetables","Red Pepper","Rote Paprika"),
    ("fruits_vegetables","Green Pepper","Grüne Paprika"),
    ("fruits_vegetables","Yellow Pepper","Gelbe Paprika"),
    ("fruits_vegetables","Chili Pepper","Chilischote"),
    ("fruits_vegetables","Jalapeño","Jalapeño"),
    ("fruits_vegetables","Zucchini","Zucchini"),
    ("fruits_vegetables","Eggplant","Aubergine"),
    ("fruits_vegetables","Broccoli","Brokkoli"),
    ("fruits_vegetables","Cauliflower","Blumenkohl"),
    ("fruits_vegetables","Cabbage","Kohl"),
    ("fruits_vegetables","Red Cabbage","Rotkohl"),
    ("fruits_vegetables","Brussels Sprouts","Rosenkohl"),
    ("fruits_vegetables","Kale","Grünkohl"),
    ("fruits_vegetables","Spinach","Spinat"),
    ("fruits_vegetables","Lettuce","Kopfsalat"),
    ("fruits_vegetables","Iceberg Lettuce","Eisbergsalat"),
    ("fruits_vegetables","Rocket","Rucola"),
    ("fruits_vegetables","Chard","Mangold"),
    ("fruits_vegetables","Leek","Lauch"),
    ("fruits_vegetables","Onion","Zwiebel"),
    ("fruits_vegetables","Red Onion","Rote Zwiebel"),
    ("fruits_vegetables","Spring Onion","Frühlingszwiebel"),
    ("fruits_vegetables","Garlic","Knoblauch"),
    ("fruits_vegetables","Shallot","Schalotte"),
    ("fruits_vegetables","Carrot","Karotte"),
    ("fruits_vegetables","Parsnip","Pastinake"),
    ("fruits_vegetables","Turnip","Rübe"),
    ("fruits_vegetables","Beetroot","Rote Bete"),
    ("fruits_vegetables","Radish","Radieschen"),
    ("fruits_vegetables","Sweet Potato","Süßkartoffel"),
    ("fruits_vegetables","Potato","Kartoffel"),
    ("fruits_vegetables","Butternut Squash","Butternusskürbis"),
    ("fruits_vegetables","Pumpkin","Kürbis"),
    ("fruits_vegetables","Corn","Mais"),
    ("fruits_vegetables","Peas","Erbsen"),
    ("fruits_vegetables","Green Beans","Grüne Bohnen"),
    ("fruits_vegetables","Asparagus","Spargel"),
    ("fruits_vegetables","Artichoke","Artischocke"),
    ("fruits_vegetables","Fennel","Fenchel"),
    ("fruits_vegetables","Celery","Sellerie"),
    ("fruits_vegetables","Celeriac","Knollensellerie"),
    ("fruits_vegetables","Mushroom","Champignon"),
    ("fruits_vegetables","Shiitake Mushroom","Shiitake-Pilz"),
    ("fruits_vegetables","Portobello Mushroom","Portobello-Pilz"),
    ("fruits_vegetables","Ginger","Ingwer"),
    ("fruits_vegetables","Turmeric","Kurkuma"),
    ("fruits_vegetables","Herbs Mix","Kräutermischung"),
    ("fruits_vegetables","Basil","Basilikum"),
    ("fruits_vegetables","Parsley","Petersilie"),
    ("fruits_vegetables","Mint","Minze"),
    ("fruits_vegetables","Rosemary","Rosmarin"),
    ("fruits_vegetables","Thyme","Thymian"),
    ("fruits_vegetables","Chives","Schnittlauch"),
    ("fruits_vegetables","Dill","Dill"),
    ("fruits_vegetables","Coriander","Koriander"),
    ("fruits_vegetables","Lemongrass","Zitronengras"),
    ("fruits_vegetables","Fig","Feige"),
    ("fruits_vegetables","Date","Dattel"),
    ("fruits_vegetables","Passion Fruit","Maracuja"),
    ("fruits_vegetables","Dragon Fruit","Drachenfrucht"),
    ("fruits_vegetables","Lychee","Litschi"),
    ("fruits_vegetables","Guava","Guave"),
    ("fruits_vegetables","Starfruit","Karambole"),
    ("fruits_vegetables","Persimmon","Kaki"),
    ("fruits_vegetables","Quince","Quitte"),
    ("fruits_vegetables","Okra","Okra"),
    ("fruits_vegetables","Bok Choy","Pak Choi"),
    ("fruits_vegetables","Endive","Endivie"),
    ("fruits_vegetables","Watercress","Brunnenkresse"),
    ("fruits_vegetables","Savoy Cabbage","Wirsing"),
    ("fruits_vegetables","Kohlrabi","Kohlrabi"),
    ("fruits_vegetables","Plantain","Kochbanane"),
    # Meat
    ("meat","Chicken Breast","Hühnerbrust"),
    ("meat","Chicken Thigh","Hähnchenschenkel"),
    ("meat","Whole Chicken","Ganzes Hähnchen"),
    ("meat","Chicken Wings","Hähnchenflügel"),
    ("meat","Turkey Breast","Putenbrust"),
    ("meat","Ground Turkey","Hackfleisch vom Truthahn"),
    ("meat","Duck Breast","Entenbrust"),
    ("meat","Beef Steak","Rindersteak"),
    ("meat","Ground Beef","Rinderhackfleisch"),
    ("meat","Beef Roast","Rinderbraten"),
    ("meat","Beef Ribs","Rinderrippen"),
    ("meat","Veal","Kalbfleisch"),
    ("meat","Pork Chop","Schweinekotelette"),
    ("meat","Pork Loin","Schweinefilet"),
    ("meat","Ground Pork","Schweinehackfleisch"),
    ("meat","Pork Ribs","Schweinerippchen"),
    ("meat","Bacon","Speck"),
    ("meat","Ham","Schinken"),
    ("meat","Salami","Salami"),
    ("meat","Sausage","Wurst"),
    ("meat","Bratwurst","Bratwurst"),
    ("meat","Chorizo","Chorizo"),
    ("meat","Prosciutto","Prosciutto"),
    ("meat","Pancetta","Pancetta"),
    ("meat","Lamb Chop","Lammkotelett"),
    ("meat","Lamb Rack","Lammrücken"),
    ("meat","Ground Lamb","Lammhackfleisch"),
    ("meat","Venison","Wildfleisch"),
    ("meat","Rabbit","Kaninchen"),
    ("meat","Liver","Leber"),
    ("meat","Beef Mince","Rindermett"),
    ("meat","Chicken Fillet","Hähnchenfilet"),
    ("meat","Turkey Mince","Putenhackfleisch"),
    ("meat","Pork Belly","Schweinebauch"),
    ("meat","Beef Brisket","Rinderbrust"),
    ("meat","Short Ribs","Short Ribs"),
    ("meat","Chicken Drumstick","Hähnchenkeulen"),
    ("meat","Beef Sirloin","Roastbeef"),
    ("meat","Beef Tenderloin","Rinderfilet"),
    ("meat","T-Bone Steak","T-Bone-Steak"),
    # Fish & Seafood
    ("fish","Salmon Fillet","Lachsfilet"),
    ("fish","Whole Salmon","Ganzer Lachs"),
    ("fish","Smoked Salmon","Räucherlachs"),
    ("fish","Tuna Steak","Thunfischsteak"),
    ("fish","Canned Tuna","Thunfisch aus der Dose"),
    ("fish","Cod Fillet","Kabeljaufilet"),
    ("fish","Haddock","Schellfisch"),
    ("fish","Tilapia","Tilapia"),
    ("fish","Sea Bass","Wolfsbarsch"),
    ("fish","Sea Bream","Dorade"),
    ("fish","Trout","Forelle"),
    ("fish","Mackerel","Makrele"),
    ("fish","Herring","Hering"),
    ("fish","Sardines","Sardinen"),
    ("fish","Anchovies","Sardellen"),
    ("fish","Shrimp","Garnelen"),
    ("fish","King Prawns","Riesengarnelen"),
    ("fish","Lobster","Hummer"),
    ("fish","Crab","Krabbe"),
    ("fish","Mussels","Miesmuscheln"),
    ("fish","Clams","Venusmuscheln"),
    ("fish","Oysters","Austern"),
    ("fish","Scallops","Jakobsmuscheln"),
    ("fish","Squid","Tintenfisch"),
    ("fish","Octopus","Tintenfisch/Oktopus"),
    ("fish","Crayfish","Flusskrebs"),
    ("fish","Fish Sticks","Fischstäbchen"),
    ("fish","Smoked Mackerel","Räuchermakrele"),
    ("fish","Swordfish","Schwertfisch"),
    ("fish","Halibut","Heilbutt"),
    # Dairy & Eggs
    ("dairy_eggs","Whole Milk","Vollmilch"),
    ("dairy_eggs","Skimmed Milk","Magermilch"),
    ("dairy_eggs","Semi-Skimmed Milk","Halbfettmilch"),
    ("dairy_eggs","Oat Milk","Hafermilch"),
    ("dairy_eggs","Almond Milk","Mandelmilch"),
    ("dairy_eggs","Soy Milk","Sojamilch"),
    ("dairy_eggs","Coconut Milk","Kokosmilch"),
    ("dairy_eggs","Butter","Butter"),
    ("dairy_eggs","Margarine","Margarine"),
    ("dairy_eggs","Heavy Cream","Sahne"),
    ("dairy_eggs","Sour Cream","Saure Sahne"),
    ("dairy_eggs","Crème Fraîche","Crème Fraîche"),
    ("dairy_eggs","Cream Cheese","Frischkäse"),
    ("dairy_eggs","Cheddar","Cheddar"),
    ("dairy_eggs","Gouda","Gouda"),
    ("dairy_eggs","Edam","Edamer"),
    ("dairy_eggs","Emmental","Emmentaler"),
    ("dairy_eggs","Brie","Brie"),
    ("dairy_eggs","Camembert","Camembert"),
    ("dairy_eggs","Mozzarella","Mozzarella"),
    ("dairy_eggs","Parmesan","Parmesan"),
    ("dairy_eggs","Feta","Feta"),
    ("dairy_eggs","Ricotta","Ricotta"),
    ("dairy_eggs","Cottage Cheese","Hüttenkäse"),
    ("dairy_eggs","Greek Yogurt","Griechischer Joghurt"),
    ("dairy_eggs","Plain Yogurt","Naturjoghurt"),
    ("dairy_eggs","Flavored Yogurt","Fruchtjoghurt"),
    ("dairy_eggs","Kefir","Kefir"),
    ("dairy_eggs","Quark","Quark"),
    ("dairy_eggs","Eggs","Eier"),
    ("dairy_eggs","Free Range Eggs","Freilandeier"),
    ("dairy_eggs","Organic Eggs","Bio-Eier"),
    ("dairy_eggs","Condensed Milk","Kondensmilch"),
    ("dairy_eggs","Evaporated Milk","Verdampfte Milch"),
    ("dairy_eggs","Whipping Cream","Schlagsahne"),
    ("dairy_eggs","Buttermilk","Buttermilch"),
    ("dairy_eggs","Mascarpone","Mascarpone"),
    ("dairy_eggs","Aged Gouda","Alter Gouda"),
    ("dairy_eggs","Gruyère","Gruyère"),
    ("dairy_eggs","Blue Cheese","Blauschimmelkäse"),
    # Bakery & Bread
    ("bakery_bread","White Bread","Weißbrot"),
    ("bakery_bread","Whole Wheat Bread","Vollkornbrot"),
    ("bakery_bread","Sourdough Bread","Sauerteigbrot"),
    ("bakery_bread","Rye Bread","Roggenbrot"),
    ("bakery_bread","Baguette","Baguette"),
    ("bakery_bread","Ciabatta","Ciabatta"),
    ("bakery_bread","Focaccia","Focaccia"),
    ("bakery_bread","Pita Bread","Pitabrot"),
    ("bakery_bread","Tortilla","Tortilla"),
    ("bakery_bread","Naan Bread","Nan-Brot"),
    ("bakery_bread","Bagel","Bagel"),
    ("bakery_bread","English Muffin","English Muffin"),
    ("bakery_bread","Croissant","Croissant"),
    ("bakery_bread","Brioche","Brioche"),
    ("bakery_bread","Burger Buns","Burgerbrötchen"),
    ("bakery_bread","Hot Dog Buns","Hotdog-Brötchen"),
    ("bakery_bread","Breadsticks","Grissini"),
    ("bakery_bread","Muffin","Muffin"),
    ("bakery_bread","Brownie","Brownie"),
    ("bakery_bread","Cake","Kuchen"),
    ("bakery_bread","Cheesecake","Käsekuchen"),
    ("bakery_bread","Donut","Donut"),
    ("bakery_bread","Danish Pastry","Dänisches Gebäck"),
    ("bakery_bread","Cinnamon Roll","Zimtschnecke"),
    ("bakery_bread","Pretzel","Brezel"),
    ("bakery_bread","Crackers","Knäckebrot"),
    ("bakery_bread","Rice Cakes","Reiswaffeln"),
    ("bakery_bread","Flatbread","Fladenbrot"),
    ("bakery_bread","Pumpernickel","Pumpernickel"),
    ("bakery_bread","Spelt Bread","Dinkelbrот"),
    # Pantry & Dry Goods
    ("pantry","White Rice","Weißer Reis"),
    ("pantry","Brown Rice","Brauner Reis"),
    ("pantry","Basmati Rice","Basmatireis"),
    ("pantry","Jasmine Rice","Jasminreis"),
    ("pantry","Arborio Rice","Arborio-Reis"),
    ("pantry","Spaghetti","Spaghetti"),
    ("pantry","Penne","Penne"),
    ("pantry","Fusilli","Fusilli"),
    ("pantry","Rigatoni","Rigatoni"),
    ("pantry","Tagliatelle","Tagliatelle"),
    ("pantry","Lasagne Sheets","Lasagneblätter"),
    ("pantry","Egg Noodles","Eiernudeln"),
    ("pantry","Rice Noodles","Reisnudeln"),
    ("pantry","Udon Noodles","Udon-Nudeln"),
    ("pantry","Quinoa","Quinoa"),
    ("pantry","Couscous","Couscous"),
    ("pantry","Bulgur","Bulgur"),
    ("pantry","Oats","Haferflocken"),
    ("pantry","Rolled Oats","Zartblatt-Haferflocken"),
    ("pantry","Cornmeal","Maismehl"),
    ("pantry","Polenta","Polenta"),
    ("pantry","Lentils","Linsen"),
    ("pantry","Red Lentils","Rote Linsen"),
    ("pantry","Chickpeas","Kichererbsen"),
    ("pantry","Black Beans","Schwarze Bohnen"),
    ("pantry","Kidney Beans","Kidneybohnen"),
    ("pantry","Cannellini Beans","Cannellini-Bohnen"),
    ("pantry","Lentil Soup","Linsensuppe"),
    ("pantry","Chickpea Flour","Kichererbsenmehl"),
    ("pantry","All-Purpose Flour","Weizenmehl"),
    ("pantry","Whole Wheat Flour","Vollkornmehl"),
    ("pantry","Bread Flour","Brotmehl"),
    ("pantry","Almond Flour","Mandelmehl"),
    ("pantry","Coconut Flour","Kokosmehl"),
    ("pantry","Cornstarch","Stärkemehl"),
    ("pantry","Baking Powder","Backpulver"),
    ("pantry","Baking Soda","Natron"),
    ("pantry","Yeast","Hefe"),
    ("pantry","Salt","Salz"),
    ("pantry","Sugar","Zucker"),
    ("pantry","Brown Sugar","Brauner Zucker"),
    ("pantry","Powdered Sugar","Puderzucker"),
    ("pantry","Honey","Honig"),
    ("pantry","Maple Syrup","Ahornsirup"),
    ("pantry","Agave Syrup","Agavensirup"),
    ("pantry","Vanilla Extract","Vanilleextrakt"),
    ("pantry","Cocoa Powder","Kakaopulver"),
    ("pantry","Dark Chocolate","Zartbitterschokolade"),
    ("pantry","Milk Chocolate","Vollmilchschokolade"),
    ("pantry","Olive Oil","Olivenöl"),
    ("pantry","Sunflower Oil","Sonnenblumenöl"),
    ("pantry","Coconut Oil","Kokosöl"),
    ("pantry","Canola Oil","Rapsöl"),
    ("pantry","Sesame Oil","Sesamöl"),
    ("pantry","Apple Cider Vinegar","Apfelessig"),
    ("pantry","White Wine Vinegar","Weißweinessig"),
    ("pantry","Balsamic Vinegar","Balsamico-Essig"),
    ("pantry","Soy Sauce","Sojasoße"),
    ("pantry","Worcestershire Sauce","Worcestershire Sauce"),
    ("pantry","Tomato Paste","Tomatenmark"),
    ("pantry","Canned Tomatoes","Dosentomaten"),
    ("pantry","Coconut Cream","Kokosnusscreme"),
    ("pantry","Vegetable Broth","Gemüsebrühe"),
    ("pantry","Chicken Broth","Hühnerbrühe"),
    ("pantry","Beef Broth","Rinderbrühe"),
    ("pantry","Canned Chickpeas","Kichererbsen aus der Dose"),
    ("pantry","Canned Lentils","Linsen aus der Dose"),
    ("pantry","Canned Corn","Mais aus der Dose"),
    ("pantry","Peanut Butter","Erdnussbutter"),
    ("pantry","Almond Butter","Mandelbutter"),
    ("pantry","Tahini","Tahini"),
    ("pantry","Jam","Marmelade"),
    ("pantry","Strawberry Jam","Erdbeermarmelade"),
    ("pantry","Apricot Jam","Aprikosenmarmelade"),
    ("pantry","Nutella","Nutella"),
    ("pantry","Marmite","Marmite"),
    # Frozen Foods
    ("frozen_foods","Frozen Peas","Tiefkühl-Erbsen"),
    ("frozen_foods","Frozen Corn","Tiefkühl-Mais"),
    ("frozen_foods","Frozen Spinach","Tiefkühl-Spinat"),
    ("frozen_foods","Frozen Broccoli","Tiefkühl-Brokkoli"),
    ("frozen_foods","Frozen Mixed Vegetables","Tiefkühl-Gemüsemischung"),
    ("frozen_foods","Frozen Edamame","Tiefkühl-Edamame"),
    ("frozen_foods","Frozen Berries","Tiefkühl-Beeren"),
    ("frozen_foods","Frozen Strawberries","Tiefkühl-Erdbeeren"),
    ("frozen_foods","Frozen Mango","Tiefkühl-Mango"),
    ("frozen_foods","Frozen Pizza","Tiefkühl-Pizza"),
    ("frozen_foods","Frozen Lasagne","Tiefkühl-Lasagne"),
    ("frozen_foods","Frozen Burger Patties","Tiefkühl-Burgerpatties"),
    ("frozen_foods","Frozen Chicken Nuggets","Tiefkühl-Chicken Nuggets"),
    ("frozen_foods","Frozen Fish Fillet","Tiefkühl-Fischfilet"),
    ("frozen_foods","Frozen Shrimp","Tiefkühl-Garnelen"),
    ("frozen_foods","Frozen Fries","Tiefkühl-Pommes"),
    ("frozen_foods","Frozen Waffles","Tiefkühl-Waffeln"),
    ("frozen_foods","Frozen Pancakes","Tiefkühl-Pfannkuchen"),
    ("frozen_foods","Ice Cream Vanilla","Vanilleeis"),
    ("frozen_foods","Ice Cream Chocolate","Schokoladeneis"),
    ("frozen_foods","Ice Cream Strawberry","Erdbeereis"),
    ("frozen_foods","Sorbet","Sorbet"),
    ("frozen_foods","Frozen Dumplings","Tiefkühl-Teigtaschen"),
    ("frozen_foods","Frozen Spring Rolls","Tiefkühl-Frühlingsrollen"),
    ("frozen_foods","Frozen Pierogi","Tiefkühl-Pierogi"),
    ("frozen_foods","Frozen Burrito","Tiefkühl-Burrito"),
    ("frozen_foods","Frozen Pot Pie","Tiefkühl-Fleischpastete"),
    ("frozen_foods","Frozen Soup","Tiefkühl-Suppe"),
    ("frozen_foods","Frozen Bread Dough","Tiefkühl-Brotteig"),
    ("frozen_foods","Frozen Hash Browns","Tiefkühl-Hash Browns"),
    # Beverages
    ("beverages","Still Water","Stilles Wasser"),
    ("beverages","Sparkling Water","Mineralwasser"),
    ("beverages","Orange Juice","Orangensaft"),
    ("beverages","Apple Juice","Apfelsaft"),
    ("beverages","Grape Juice","Traubensaft"),
    ("beverages","Tomato Juice","Tomatensaft"),
    ("beverages","Lemonade","Limonade"),
    ("beverages","Cola","Cola"),
    ("beverages","Diet Cola","Cola light"),
    ("beverages","Sparkling Lemon","Zitronenlimonade"),
    ("beverages","Energy Drink","Energydrink"),
    ("beverages","Iced Tea","Eistee"),
    ("beverages","Green Tea","Grüner Tee"),
    ("beverages","Black Tea","Schwarzer Tee"),
    ("beverages","Herbal Tea","Kräutertee"),
    ("beverages","Chamomile Tea","Kamillentee"),
    ("beverages","Peppermint Tea","Pfefferminztee"),
    ("beverages","Coffee Beans","Kaffeebohnen"),
    ("beverages","Ground Coffee","Gemahlener Kaffee"),
    ("beverages","Instant Coffee","Instantkaffee"),
    ("beverages","Espresso Pods","Espresso-Kapseln"),
    ("beverages","Hot Chocolate","Heiße Schokolade"),
    ("beverages","Protein Shake","Proteinshake"),
    ("beverages","Smoothie","Smoothie"),
    ("beverages","Coconut Water","Kokoswasser"),
    ("beverages","Kombucha","Kombucha"),
    ("beverages","Vegetable Juice","Gemüsesaft"),
    ("beverages","Cranberry Juice","Cranberrysaft"),
    # Snacks & Sweets
    ("snacks_sweets","Potato Chips","Kartoffelchips"),
    ("snacks_sweets","Tortilla Chips","Tortillachips"),
    ("snacks_sweets","Popcorn","Popcorn"),
    ("snacks_sweets","Pretzels","Brezel-Snacks"),
    ("snacks_sweets","Rice Crackers","Reiscracker"),
    ("snacks_sweets","Peanuts","Erdnüsse"),
    ("snacks_sweets","Cashews","Cashewnüsse"),
    ("snacks_sweets","Almonds","Mandeln"),
    ("snacks_sweets","Walnuts","Walnüsse"),
    ("snacks_sweets","Trail Mix","Nussmischung"),
    ("snacks_sweets","Granola Bar","Müsliriegel"),
    ("snacks_sweets","Protein Bar","Proteinriegel"),
    ("snacks_sweets","Cereal Bar","Getreideriegel"),
    ("snacks_sweets","Gummy Bears","Gummibären"),
    ("snacks_sweets","Chocolate Bar","Schokoriegel"),
    ("snacks_sweets","Kit Kat","Kit Kat"),
    ("snacks_sweets","Snickers","Snickers"),
    ("snacks_sweets","Twix","Twix"),
    ("snacks_sweets","Oreo","Oreo"),
    ("snacks_sweets","Digestive Biscuits","Digestive Kekse"),
    ("snacks_sweets","Shortbread","Shortbread"),
    ("snacks_sweets","Wafer","Waffelgebäck"),
    ("snacks_sweets","Candy","Bonbons"),
    ("snacks_sweets","Lollipop","Lutscher"),
    ("snacks_sweets","Chewing Gum","Kaugummi"),
    ("snacks_sweets","Fruit Gummies","Fruchtgummi"),
    ("snacks_sweets","Jelly Beans","Jelly Beans"),
    ("snacks_sweets","Marshmallow","Marshmallow"),
    ("snacks_sweets","Dark Chocolate Squares","Zartbitterschokolade-Stücke"),
    ("snacks_sweets","Mints","Pfefferminzdrops"),
    ("snacks_sweets","Beef Jerky","Beef Jerky"),
    ("snacks_sweets","Dried Mango","Getrocknete Mango"),
    ("snacks_sweets","Dried Cranberries","Getrocknete Cranberries"),
    ("snacks_sweets","Sunflower Seeds","Sonnenblumenkerne"),
    ("snacks_sweets","Pumpkin Seeds","Kürbiskerne"),
    ("snacks_sweets","Sesame Snaps","Sesam-Snaps"),
    # Condiments & Spices
    ("condiments_spices","Ketchup","Ketchup"),
    ("condiments_spices","Mustard","Senf"),
    ("condiments_spices","Dijon Mustard","Dijon-Senf"),
    ("condiments_spices","Mayonnaise","Mayonnaise"),
    ("condiments_spices","Barbecue Sauce","Barbecue-Soße"),
    ("condiments_spices","Hot Sauce","Scharfe Soße"),
    ("condiments_spices","Sriracha","Sriracha"),
    ("condiments_spices","Tabasco","Tabasco"),
    ("condiments_spices","Teriyaki Sauce","Teriyaki-Soße"),
    ("condiments_spices","Hoisin Sauce","Hoisin-Soße"),
    ("condiments_spices","Fish Sauce","Fischsoße"),
    ("condiments_spices","Oyster Sauce","Austernsoße"),
    ("condiments_spices","Sweet Chili Sauce","Süß-Chili-Soße"),
    ("condiments_spices","Pesto","Pesto"),
    ("condiments_spices","Hummus","Hummus"),
    ("condiments_spices","Guacamole","Guacamole"),
    ("condiments_spices","Salsa","Salsa"),
    ("condiments_spices","Ranch Dressing","Ranch-Dressing"),
    ("condiments_spices","Caesar Dressing","Caesar-Dressing"),
    ("condiments_spices","Italian Dressing","Italienisches Dressing"),
    ("condiments_spices","Black Pepper","Schwarzer Pfeffer"),
    ("condiments_spices","White Pepper","Weißer Pfeffer"),
    ("condiments_spices","Paprika Powder","Paprikapulver"),
    ("condiments_spices","Cayenne Pepper","Cayennepfeffer"),
    ("condiments_spices","Cumin","Kreuzkümmel"),
    ("condiments_spices","Coriander Seeds","Koriandersamen"),
    ("condiments_spices","Cinnamon","Zimt"),
    ("condiments_spices","Nutmeg","Muskatnuss"),
    ("condiments_spices","Cloves","Nelken"),
    ("condiments_spices","Cardamom","Kardamom"),
    ("condiments_spices","Turmeric Powder","Kurkumapulver"),
    ("condiments_spices","Curry Powder","Currypulver"),
    ("condiments_spices","Garam Masala","Garam Masala"),
    ("condiments_spices","Bay Leaves","Lorbeerblätter"),
    ("condiments_spices","Oregano","Oregano"),
    ("condiments_spices","Basil Dried","Getrocknetes Basilikum"),
    ("condiments_spices","Thyme Dried","Getrockneter Thymian"),
    ("condiments_spices","Chili Flakes","Chiliflocken"),
    ("condiments_spices","Garlic Powder","Knoblauchpulver"),
    ("condiments_spices","Onion Powder","Zwiebelpulver"),
    ("condiments_spices","Smoked Paprika","Geräuchertes Paprikapulver"),
    ("condiments_spices","Mixed Herbs","Kräutermischung"),
    ("condiments_spices","Vanilla Bean","Vanilleschote"),
    ("condiments_spices","Star Anise","Sternanis"),
    ("condiments_spices","Saffron","Safran"),
    ("condiments_spices","Capers","Kapern"),
    ("condiments_spices","Pickles","Gewürzgurken"),
    ("condiments_spices","Olives","Oliven"),
    ("condiments_spices","Sun-Dried Tomatoes","Getrocknete Tomaten"),
    # Health & Beauty
    ("health_beauty","Toothpaste","Zahnpasta"),
    ("health_beauty","Toothbrush","Zahnbürste"),
    ("health_beauty","Dental Floss","Zahnseide"),
    ("health_beauty","Mouthwash","Mundspülung"),
    ("health_beauty","Shampoo","Shampoo"),
    ("health_beauty","Conditioner","Haarspülung"),
    ("health_beauty","Body Wash","Duschgel"),
    ("health_beauty","Bar Soap","Seife"),
    ("health_beauty","Face Wash","Gesichtsreinigung"),
    ("health_beauty","Moisturizer","Feuchtigkeitscreme"),
    ("health_beauty","Sunscreen","Sonnencreme"),
    ("health_beauty","Lip Balm","Lippenbalsam"),
    ("health_beauty","Deodorant","Deodorant"),
    ("health_beauty","Antiperspirant","Antitranspirant"),
    ("health_beauty","Razor","Rasierer"),
    ("health_beauty","Shaving Cream","Rasiercreme"),
    ("health_beauty","Aftershave","Aftershave"),
    ("health_beauty","Hand Cream","Handcreme"),
    ("health_beauty","Nail Clippers","Nagelschere"),
    ("health_beauty","Cotton Pads","Wattepads"),
    ("health_beauty","Cotton Buds","Wattestäbchen"),
    ("health_beauty","Bandages","Pflaster"),
    ("health_beauty","Paracetamol","Paracetamol"),
    ("health_beauty","Ibuprofen","Ibuprofen"),
    ("health_beauty","Vitamins","Vitamine"),
    ("health_beauty","Vitamin C","Vitamin C"),
    ("health_beauty","Multivitamin","Multivitamin"),
    ("health_beauty","Protein Powder","Proteinpulver"),
    ("health_beauty","Fish Oil","Fischöl"),
    ("health_beauty","Collagen Supplements","Kollagenpräparate"),
    # Household & Cleaning
    ("household_cleaning","Dish Soap","Spülmittel"),
    ("household_cleaning","Dishwasher Tablets","Geschirrspültabs"),
    ("household_cleaning","Dishwasher Powder","Geschirrspülpulver"),
    ("household_cleaning","Laundry Detergent","Waschmittel"),
    ("household_cleaning","Fabric Softener","Weichspüler"),
    ("household_cleaning","Stain Remover","Fleckenentferner"),
    ("household_cleaning","All-Purpose Cleaner","Allzweckreiniger"),
    ("household_cleaning","Bathroom Cleaner","Badreiniger"),
    ("household_cleaning","Toilet Cleaner","WC-Reiniger"),
    ("household_cleaning","Floor Cleaner","Bodenreiniger"),
    ("household_cleaning","Glass Cleaner","Glasreiniger"),
    ("household_cleaning","Oven Cleaner","Ofenreiniger"),
    ("household_cleaning","Bleach","Bleichmittel"),
    ("household_cleaning","Paper Towels","Küchenpapier"),
    ("household_cleaning","Toilet Paper","Toilettenpapier"),
    ("household_cleaning","Trash Bags","Müllbeutel"),
    ("household_cleaning","Zip Lock Bags","Gefrierbeutel"),
    ("household_cleaning","Aluminum Foil","Aluminiumfolie"),
    ("household_cleaning","Plastic Wrap","Frischhaltefolie"),
    ("household_cleaning","Baking Paper","Backpapier"),
    ("household_cleaning","Sponge","Schwamm"),
    ("household_cleaning","Scrubbing Brush","Scheuerbürste"),
    ("household_cleaning","Mop","Wischmopp"),
    ("household_cleaning","Broom","Besen"),
    ("household_cleaning","Dustpan","Kehrschaufel"),
    ("household_cleaning","Air Freshener","Raumduft"),
    ("household_cleaning","Candle","Kerze"),
    ("household_cleaning","Matches","Streichhölzer"),
    ("household_cleaning","Batteries","Batterien"),
    ("household_cleaning","Light Bulbs","Glühbirnen"),
    # Baby Care
    ("baby_care","Baby Food Purée","Babybreipüree"),
    ("baby_care","Baby Cereal","Babybrei"),
    ("baby_care","Baby Formula","Säuglingsnahrung"),
    ("baby_care","Baby Snacks","Babysnacks"),
    ("baby_care","Baby Juice","Babysaft"),
    ("baby_care","Diapers","Windeln"),
    ("baby_care","Baby Wipes","Babyfeuchttücher"),
    ("baby_care","Baby Shampoo","Babyshampoo"),
    ("baby_care","Baby Lotion","Babylotion"),
    ("baby_care","Baby Oil","Babyöl"),
    ("baby_care","Baby Powder","Babypuder"),
    ("baby_care","Baby Toothbrush","Babyzahnbürste"),
    ("baby_care","Pacifier","Schnuller"),
    ("baby_care","Baby Bottle","Babyflasche"),
    ("baby_care","Teether","Beißring"),
    ("baby_care","Diaper Rash Cream","Wundschutzcreme"),
    # Pets
    ("pets","Dry Dog Food","Trockenfutter für Hunde"),
    ("pets","Wet Dog Food","Nassfutter für Hunde"),
    ("pets","Dog Treats","Hundekekse"),
    ("pets","Dry Cat Food","Trockenfutter für Katzen"),
    ("pets","Wet Cat Food","Nassfutter für Katzen"),
    ("pets","Cat Treats","Katzensnacks"),
    ("pets","Cat Litter","Katzenstreu"),
    ("pets","Bird Food","Vogelfutter"),
    ("pets","Fish Food","Fischfutter"),
    ("pets","Hamster Food","Hamsterfutter"),
    ("pets","Rabbit Pellets","Kaninchenpellets"),
    ("pets","Pet Shampoo","Tiershampoo"),
    ("pets","Flea Treatment","Flohbehandlung"),
    ("pets","Dog Poop Bags","Hundekotbeutel"),
    ("pets","Pet Vitamins","Tiervitamine"),
    # Deli & Prepared Foods
    ("deli_prepared","Hummus","Hummus"),
    ("deli_prepared","Tzatziki","Tzatziki"),
    ("deli_prepared","Ready Meal Pasta","Fertiggericht Pasta"),
    ("deli_prepared","Ready Meal Curry","Fertiggericht Curry"),
    ("deli_prepared","Soup Cup","Suppenbecher"),
    ("deli_prepared","Sushi","Sushi"),
    ("deli_prepared","Sandwich","Sandwich"),
    ("deli_prepared","Wrap","Wrap"),
    ("deli_prepared","Quiche","Quiche"),
    ("deli_prepared","Rotisserie Chicken","Brathähnchen"),
    ("deli_prepared","Cooked Ham","Gekochter Schinken"),
    ("deli_prepared","Smoked Turkey","Geräucherter Truthahn"),
    ("deli_prepared","Roast Beef Slices","Roastbeefscheiben"),
    ("deli_prepared","Pastrami","Pastrami"),
    ("deli_prepared","Mortadella","Mortadella"),
    ("deli_prepared","Pepperoni","Pepperoni"),
    ("deli_prepared","Liverwurst","Leberwurst"),
    ("deli_prepared","Potato Salad","Kartoffelsalat"),
    ("deli_prepared","Coleslaw","Coleslaw"),
    ("deli_prepared","Tabouli","Taboulé"),
    # Alcohol
    ("alcohol","Lager Beer","Lagerbier"),
    ("alcohol","Craft Beer","Craftbier"),
    ("alcohol","Wheat Beer","Weizenbier"),
    ("alcohol","Dark Beer","Dunkles Bier"),
    ("alcohol","Non-Alcoholic Beer","Alkoholfreies Bier"),
    ("alcohol","White Wine","Weißwein"),
    ("alcohol","Red Wine","Rotwein"),
    ("alcohol","Rosé Wine","Roséwein"),
    ("alcohol","Sparkling Wine","Sekt"),
    ("alcohol","Champagne","Champagner"),
    ("alcohol","Prosecco","Prosecco"),
    ("alcohol","Vodka","Wodka"),
    ("alcohol","Gin","Gin"),
    ("alcohol","Rum","Rum"),
    ("alcohol","Whisky","Whisky"),
    ("alcohol","Tequila","Tequila"),
    ("alcohol","Brandy","Weinbrand"),
    ("alcohol","Liqueur","Likör"),
    ("alcohol","Aperol","Aperol"),
    ("alcohol","Vermouth","Wermut"),
    ("alcohol","Cider","Apfelwein"),
    ("alcohol","Hard Seltzer","Hard Seltzer"),
    ("alcohol","Sake","Sake"),
    ("alcohol","Mead","Met"),
    # Organic & Natural
    ("organic","Organic Honey","Bio-Honig"),
    ("organic","Organic Oats","Bio-Haferflocken"),
    ("organic","Organic Quinoa","Bio-Quinoa"),
    ("organic","Organic Olive Oil","Bio-Olivenöl"),
    ("organic","Organic Coconut Oil","Bio-Kokosöl"),
    ("organic","Organic Green Tea","Bio-Grüntee"),
    ("organic","Organic Herbal Tea","Bio-Kräutertee"),
    ("organic","Organic Almond Milk","Bio-Mandelmilch"),
    ("organic","Organic Tofu","Bio-Tofu"),
    ("organic","Organic Tempeh","Bio-Tempeh"),
    ("organic","Organic Soy Milk","Bio-Sojamilch"),
    ("organic","Organic Dark Chocolate","Bio-Zartbitterschokolade"),
    ("organic","Organic Maple Syrup","Bio-Ahornsirup"),
    ("organic","Organic Granola","Bio-Granola"),
    ("organic","Organic Lentils","Bio-Linsen"),
    ("organic","Organic Chickpeas","Bio-Kichererbsen"),
    ("organic","Organic Brown Rice","Bio-Brauner Reis"),
    ("organic","Organic Pasta","Bio-Nudeln"),
    ("organic","Organic Almonds","Bio-Mandeln"),
    ("organic","Organic Peanut Butter","Bio-Erdnussbutter"),
    # International Foods
    ("international","Miso Paste","Misopaste"),
    ("international","Kimchi","Kimchi"),
    ("international","Nori Seaweed","Nori-Algen"),
    ("international","Panko Breadcrumbs","Panko-Semmelbrösel"),
    ("international","Coconut Aminos","Kokosaminos"),
    ("international","Gochujang","Gochujang"),
    ("international","Curry Paste","Currypaste"),
    ("international","Red Curry Paste","Rote Currypaste"),
    ("international","Green Curry Paste","Grüne Currypaste"),
    ("international","Harissa","Harissa"),
    ("international","Tahini","Tahini"),
    ("international","Za'atar","Za'atar"),
    ("international","Sumac","Sumach"),
    ("international","Preserved Lemons","Eingelegte Zitronen"),
    ("international","Rose Water","Rosenwasser"),
    ("international","Wonton Wrappers","Wan-Tan-Teigblätter"),
    ("international","Spring Roll Wrappers","Frühlingsrollenteigblätter"),
    ("international","Rice Paper","Reispapier"),
    ("international","Dashi Stock","Dashi-Brühe"),
    ("international","Mirin","Mirin"),
    ("international","Ponzu Sauce","Ponzu-Soße"),
    ("international","Black Bean Sauce","Schwarzbohnensauce"),
    ("international","Satay Sauce","Satay-Soße"),
    ("international","Coconut Vinegar","Kokosnussessig"),
    ("international","Plantain Flour","Kochbananenmehl"),
    ("international","Tapioca Starch","Tapiokastärke"),
    ("international","Cassava Flour","Maniokmehl"),
]


def esc(s):
    return s.replace("'", "''")

lines = []

# Categories
for key, names in CATEGORIES.items():
    t = json.dumps(names, ensure_ascii=False)
    lines.append(
        f"INSERT INTO public.categories (key, name_translations) VALUES ('{key}', '{esc(t)}'::jsonb) "
        f"ON CONFLICT (key) DO UPDATE SET name_translations = EXCLUDED.name_translations;"
    )

lines.append("")

# Products — use subquery to look up category_id
for cat_key, en, de in PRODUCTS:
    t = json.dumps({"en": en, "de": de}, ensure_ascii=False)
    lines.append(
        f"INSERT INTO public.global_items (category_id, name_translations) "
        f"SELECT id, '{esc(t)}'::jsonb FROM public.categories WHERE key = '{cat_key}' "
        f"ON CONFLICT DO NOTHING;"
    )

print(f"-- Total products: {len(PRODUCTS)}")
with open("seed.sql", "w") as f:
    f.write("\n".join(lines))
print("Written to seed.sql")
